spring:
  application:
    name: MasqueradeBot
  datasource:
    url: jdbc:postgresql://localhost:5432/masqueradeBot
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      # ddl-auto: create  чтобы база создавалась при запуске (none-не создавалась)
      ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          show_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
telegram:
  bot:
    username: /@MasqueradeGameBot
    token: 7706965489:AAHR6381gywXExGNddCSE_JgDQ-ulpij_YI
logging:
  level:
    com.example.telegrambot: INFO
